### ISSUE TITLE
Username Password not working

### ISSUE THREAD

**Issue by anishratnam** [oldauntie/ababu#1]
The username and password provided with the installation doesn't seem to work.
<img width="513" alt="Screenshot 2019-11-11 00 54 34" src="https://user-images.githubusercontent.com/10955992/68550625-e3c32080-041d-11ea-88f7-fdb544b50d30.png">

**Comment by oldauntie** [comment]
Hi Anish, thank you for you submission.
According to what I see, problem in in database configuration (see red dot on bottom left corner).
It seems that the database connection in not configured or database is not available.
Please, check you have imported the SQL script into a MariaDB/Mysql database and/or check database connection by clicking the small gear on the bottom right side of the login window.
 
Please follow this installation instructions
http://www.oldauntie.org/ababu-installation/ for further help.
Don't esitate to write back again if something is not clear or not working.
Regards,
OldAuntie development team

**Comment by anishratnam** [comment]
Hi,

Thanks for the prompt reply. Can you please help me configure this if
possible?

It's a bit of an urgent request.

I hope you'll be able to help me.

Regards,

Anish

**Comment by anishratnam** [comment]
Updates:

I created the DB ababu.

On running the script, I get an error message.  Screenshot attached.

How much CPU would I need to do the installation.  I am using an AWS t2
small instance.

The query seems to be timing out.

Regards,

Anish

**Comment by oldauntie** [comment]
Hi there,
never tried to configure over AWS.
Have you tried to import directly from mysql (or mariadb) executable ?

mysql -u username -p database_name < file.sql

Timeout can happen with slow CPU and particular phpMyAfmin configuration.
If you want we can talk using skype.
Please let me known.

**Comment by anishratnam** [comment]
Can we talk using Zoom?

**Comment by oldauntie** [comment]
Yes sure.
   Roberto, one of our developer is available in the next hour.
   Please contact him at 609-397-7247 ora arrange a call by writing ti this email address (att: Roberto)
   Regards

   Da: "Anish Ratnam" notifications@github.com
   A: "oldauntie/ababu" ababu@noreply.github.com
   Cc: "Margaret Marple" oldauntie@oldauntie.org,"Comment" comment@noreply.github.com
   Data: Mon, 11 Nov 2019 06:59:09 -0800
   Oggetto: Re: [oldauntie/ababu] Username Password not working (#1)
   Can we talk using Zoom?

**Comment by oldauntie** [comment]
Sure.

**Comment by anishratnam** [comment]
Oops, just saw this.

Thanks.  I'll contact Roberto.

**Comment by anishratnam** [comment]
Thank you for your response
