### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [oldauntie/ababu#5]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the [AGPL-3.0-or-later](https://www.gnu.org/licenses/agpl-3.0.html) license so that others are encouraged to contribute changes back to your project.

**Comment by oldauntie** [comment]
thank you very much for your suggestion.
We are really thinking about it and seems to be a great solution. Thank you very much.
PS: Please consider to partecipate to the development.

**Comment by TechnologyClassroom** [comment]
If you decide to go with [AGPL-3.0-or-later](https://www.gnu.org/licenses/agpl-3.0.html), I can make my first PR helping with that.

**Comment by oldauntie** [comment]
Ababu License modified into AGPL-3.0-or-later. Thank you for your support. Hope to see you soon.
